### ISSUE TITLE
Long term variations in time of equinox are wrong

### ISSUE THREAD

**Issue by MartinDix** [CliMA/Insolation.jl#27]
https://gist.github.com/MartinDix/617152231ff4b4d87ac71a2e4e159a5d calculates the time of the vernal equinox using Insolation.jl. Comparing to data from http://cococubed.asu.edu/data/equinox.dat shows an incorrect long term variation.

![equinox](https://user-images.githubusercontent.com/1627802/143167027-f11924b4-d9b7-4ba2-816e-0976735e2fc7.png)

However the long term variation in date of perihelion is correct. Calculation with https://gist.github.com/MartinDix/33396874bbddc1f40049e778af68ac58,  data from http://astropixels.com/ephemeris/ephemeris.html).

![perihelion](https://user-images.githubusercontent.com/1627802/143179450-d5970770-ac0b-4221-93b9-6466b4cd3c09.png)

I believe the equinox error is because the distance_declination function uses the anomalistic year (time between passes through perihelion) rather than the tropical year (time between equinoxes). If the function is modified to use a tropical year of 365.2424 days the equinox is calculated correctly, but the time variation of the perihelion is then messed up. 

I confess I'm confused about whether the anomalies in this function refer to equinoxes or perihelion, so at the moment I can't suggest a fix which gets both the equinox and perihelion correct.

**Comment by claresinger** [comment]
@MartinDix Sorry for the very, very slow response. But thank you so much for finding this issue and pointing it out! The code has been updated now to have proper variations in orbital parameters due to Milankovitch cycles and now correctly predicts the observed centennial variations in timing of the equinox and perihelion. Your gists have been modified and added as tests of the code and to the [documentation](https://clima.github.io/Insolation.jl/dev/Milankovitch/#Variations-in-date-of-vernal-equinox-and-perihelion-on-centennial-timescales).
